# Generated by Django 4.2.7 on 2025-06-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="fingerprint",
            field=models.CharField(default="temp", max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="transcript",
            unique_together={("user", "fingerprint")},
        ),
    ]
