# Generated by Django 4.2.7 on 2025-06-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorial",
            old_name="examples",
            new_name="tips",
        ),
    ]
