# Generated by Django 4.2.7 on 2025-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorial",
            name="content",
        ),
        migrations.AddField(
            model_name="tutorial",
            name="content_md",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="duration_estimate",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="examples",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="introduction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="steps",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="summary",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
