# Generated by Django 4.2.7 on 2025-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_rename_examples_to_tips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tips",
            field=models.JSONField(
                default=list, help_text="Array of practical tips as strings"
            ),
        ),
    ]
