# Generated by Django 4.2.7 on 2025-06-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_update_tutorial_structure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorial",
            name="content_md",
        ),
    ]
